### ISSUE TITLE
Config file (infernalexp-client.toml) generates as blank

### ISSUE THREAD

**Issue by megatrook** [infernalexp/Infernal-Expansion#7]
I recently upgraded to the most recent version of Infernal Expansion, and wanted to check the new config settings. But, when i load up the game with the mod installed, the config file in my configs folder generates completely blank, with nothing in it.

**Comment by SwanX1** [comment]
This is supposed to happen, the config `.minecraft/config/infernalexp-client.toml` is for client-side configuration only. The server-side config is located in `.minecraft/saves/<your world>/serverconfig/infernalexp-server.toml`
