### ISSUE TITLE
Game crashes after load saying "java.lang.ExceptionInInitializerError: null"

### ISSUE THREAD

**Issue by dabomb6405** [infernalexp/Infernal-Expansion#9]
[crash-2021-01-09_17.40.08-fml.txt](https://github.com/infernalexp/Infernal-Expansion/files/5792046/crash-2021-01-09_17.40.08-fml.txt)
Crash Report

**Comment by CaelWarner** [comment]
Were you trying to compile the master branch yourself?

**Comment by dabomb6405** [comment]
Yeah..?

**Comment by CaelWarner** [comment]
Alright, we'll look in to it. Just keep in mind that the master branch is the branch that is under development so there are expected to be bugs and issues.

**Comment by CaelWarner** [comment]
Oh, and I forgot to say, thanks.
